language: cpp
os: linux
compiler: gcc

before_install:
  - sudo apt-get install -y libzip-dev libboost-dev libboost-program-options-dev libboost-test-dev
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/s/spdlog/libspdlog-dev_1.6-1_amd64.deb
  - sudo dpkg -i libspdlog-dev_1.6-1_amd64.deb
addons:
  apt:
    update: true

script:
  - cmake -H. -Bbuild -DFMI4CPP_USING_VCPKG=OFF -DFMI4CPP_WITH_ODEINT=ON -DFMI4CPP_WITH_CURL=OFF -DFMI4CPP_BUILD_TESTS=ON -DFMI4CPP_BUILD_EXAMPLES=ON
  - cmake --build build
  - cd build/tests && ctest