version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - cd c:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - .\vcpkg install boost-property-tree boost-ublas boost-odeint boost-program-options libzip[core] spdlog curl --triplet x64-windows
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" . -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DFMI4CPP_USING_VCPKG=ON -DFMI4CPP_WITH_CURL=ON -DFMI4CPP_WITH_ODEINT=ON -DFMI4CPP_BUILD_TOOL=ON -DFMI4CPP_BUILD_TESTS=OFF -DFMI4CPP_BUILD_EXAMPLES=ON

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

cache: c:\tools\vcpkg\installed\