trigger:
  - master

jobs:

  - job: conan
    timeoutInMinutes: 45

    pool:
      vmImage: 'vs2017-win2016'

    steps:

      - task: Bash@3
        inputs:
          script: |
            pip install conan --upgrade
            conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
            conan install . -s build_type=Debug --install-folder=build
          workingDirectory: '$(system.defaultWorkingDirectory)'
          targetType: inline

      - task: CMake@1
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/build'
          cmakeArgs: '.. -DFMI4CPP_USING_CONAN=ON -DFMI4CPP_WITH_ODEINT=ON -DFMI4CPP_BUILD_TESTS=ON -A x64'

      - task: CMake@1
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/build'
          cmakeArgs: '--build .'

      - task: Bash@3
        inputs:
          script: 'ctest -C Debug'
          workingDirectory: '$(system.defaultWorkingDirectory)/build/tests'
          targetType: inline
