version: 2
jobs:
  apt-get:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing tools & dev dependencies
          command: 'apt-get update && apt-get install -y gcc g++ cmake libzip-dev libboost-dev libboost-program-options-dev libboost-test-dev libspdlog-dev'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild -DFMI4CPP_USING_VCPKG=OFF -DFMI4CPP_WITH_ODEINT=ON -DFMI4CPP_BUILD_TOOL=ON -DFMI4CPP_BUILD_TESTS=ON -DFMI4CPP_BUILD_EXAMPLES=ON'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - store_artifacts:
          path: 'build/tool/fmu_driver'
          destination: 'fmu_driver'
      - run:
          name: Unit tests
          command: 'cd build/tests && ctest'
  vcpkg:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing tools
          command: 'apt-get update && apt-get install -y gcc g++ cmake git curl unzip tar'
      - run:
          name: Installing vcpkg
          command: 'git clone https://github.com/Microsoft/vcpkg.git'
      - run:
          name: Creating Binary Files
          command: 'cd vcpkg && ./bootstrap-vcpkg.sh'
      - run:
          name: Unit test 1
          command: 'cd vcpkg && ./vcpkg install boost-property-tree libzip[core] spdlog'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -DFMI4CPP_USING_VCPKG=ON -DFMI4CPP_WITH_ODEINT=OFF -DFMI4CPP_BUILD_TOOL=OFF -DFMI4CPP_BUILD_TESTS=OFF -DFMI4CPP_BUILD_EXAMPLES=OFF'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
workflows:
  version: 2
  build:
    jobs:
      - apt-get
      - vcpkg
