version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get install -y gcc g++'
      - run:
         name: Install Cmake
         command: 'sudo apt-get install -y cmake'
      - run:
          name: Install dependencies
          command: 'sudo apt-get install -y libzip-dev libboost-dev libboost-test-dev'
      - run:
         name: Creating Build Files
         command: 'cmake -H. -Bbuild -DFMI4CPP_USING_VCPKG=OFF -DFMI4CPP_WITH_ODEINT=OFF -DFMI4CPP_BUILD_TOOL=OFF -DFMI4CPP_BUILD_TESTS=ON'
      - run:
         name: Creating Binary Files
         command: 'cmake --build build'
      - run:
         name: Unit test 1
         command: 'cd build/tests && ./test_model_description1 --run_test=ControlledTemperature_test1 --logger=HRF,all --color_output=false --report_format=HRF --show_progress=no'
      - run:
         name: Unit test 2
         command: 'cd build/tests && ./test_model_description2 --run_test=FmuExportCrossCompile_test1 --logger=HRF,all --color_output=false --report_format=HRF --show_progress=no'
