version: 2
jobs:
  apt-get:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing tools and libraries
          command: 'apt-get update && apt-get install -y sudo gcc g++ cmake libcurl4-openssl-dev libzip-dev libboost-dev libboost-program-options-dev libboost-test-dev libspdlog-dev && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Configuring
          command: 'cmake -H. -Bbuild -DFMI4CPP_USING_VCPKG=OFF -DFMI4CPP_WITH_ODEINT=ON -DFMI4CPP_WITH_CURL=ON -DFMI4CPP_BUILD_TOOL=ON -DFMI4CPP_BUILD_TESTS=ON -DFMI4CPP_BUILD_EXAMPLES=ON'
      - run:
          name: Building
          command: 'cmake --build build'
      - store_artifacts:
          path: 'build/tool/fmu_driver'
          destination: 'fmu_driver'
      - run:
          name: Unit tests
          command: 'cd build/tests && ctest'
  conan:
    docker:
      - image: lasote/conangcc7
    steps:
      - checkout
      - run:
          name: Update conan
          command: 'sudo pip install conan --upgrade'
      - run:
          name: Conan install
          command: 'conan install . -s build_type=Debug -s compiler.libcxx=libstdc++11 --install-folder=build'
      - run:
          name: Configuring
          command: 'cmake -H. -Bbuild -DFMI4CPP_USING_VCPKG=OFF -DFMI4CPP_USING_CONAN=ON -DFMI4CPP_WITH_ODEINT=ON -DFMI4CPP_WITH_CURL=OFF -DFMI4CPP_BUILD_TOOL=OFF -DFMI4CPP_BUILD_TESTS=ON -DFMI4CPP_BUILD_EXAMPLES=ON'
      - run:
          name: Unit tests
          command: 'cd build/tests && ctest'
  vcpkg:
    docker:
      - image: laht/vcpkg
    steps:
      - checkout
      - run:
          name: Update vcpkg
          command: 'cd /home/vcpkg && git pull'
      - run:
          name: Install dependencies
          command: 'cd /home/vcpkg && ./vcpkg install boost-property-tree libzip[core] spdlog'
      - run:
          name: Configuring
          command: 'cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=/home/vcpkg/scripts/buildsystems/vcpkg.cmake -DFMI4CPP_USING_VCPKG=ON -DFMI4CPP_WITH_CURL=OFF -DFMI4CPP_WITH_ODEINT=OFF -DFMI4CPP_BUILD_TOOL=OFF -DFMI4CPP_BUILD_TESTS=OFF -DFMI4CPP_BUILD_EXAMPLES=ON'
      - run:
          name: Building
          command: 'cmake --build build'
workflows:
  version: 2
  build:
    jobs:
      - apt-get
      - vcpkg
      - conan
