version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Print the Current Time
          command: date
      - run:
      name: Installing GCC
      command: 'apt-get update && apt-get install -y gcc g++'
       - run:
           name: Install CMAKE
           command: 'apt-get update && sudo apt-get install -y cmake libzip-dev boost-program-options1.65.1'
       - run:
           name: Creating Build Files
           command: 'cmake -H. -Bbuild -DFMI4CPP_USING_VCPKG=OFF -DFMI4CPP_WITH_ODEINT=OFF -DFMI4CPP_BUILD_TOOL=OFF -DFMI4CPP_BUILD_TESTS=ON'
       - run:
           name: Creating Binary Files
           command: 'cmake --build build'
       - run:
           name: Unit Testing
           command: '/home/laht/Documents/FMI4cpp/cmake-build-debug/tests/test_model_description1 --run_test=ControlledTemperature_test1 --logger=HRF,all --color_output=false --report_format=HRF --show_progress=no'